export const questions = [
    {
        id: 1,
        question: 'Messi được xem là gì trong làng bóng đá?',
        a: 'Một cầu thủ bình thường',
        b: 'Thủ môn xuất sắc nhất',
        c: 'GOAT (vĩ đại nhất mọi thời đại)',
        d: 'Cầu thủ trẻ triển vọng',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 2,
        question: 'Chelsea là đội bóng vĩ đại nhất ở thành phố nào?',
        a: 'Manchester',
        b: 'London',
        c: 'Liverpool',
        d: 'Birmingham',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 3,
        question: 'Lionel Messi từng chơi lâu năm cho đội bóng nào?',
        a: 'Real Madrid',
        b: 'Manchester United',
        c: 'Barcelona',
        d: 'Juventus',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 4,
        question: 'Đội nào giành nhiều chức vô địch Champions League nhất?',
        a: 'Real Madrid',
        b: 'Barcelona',
        c: 'AC Milan',
        d: 'Bayern Munich',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 5,
        question: 'Cristiano Ronaldo hiện đang chơi cho đội bóng nào?',
        a: 'Manchester United',
        b: 'Chelsea',
        c: 'Barcelona',
        d: 'Liverpool',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 6,
        question: 'Giải bóng đá nào được xem là hàng đầu châu Âu?',
        a: 'La Liga',
        b: 'Serie A',
        c: 'Premier League',
        d: 'Bundesliga',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 7,
        question: 'Đội tuyển quốc gia nào từng vô địch World Cup nhiều nhất?',
        a: 'Brazil',
        b: 'Germany',
        c: 'Argentina',
        d: 'Italy',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 8,
        question: 'Sân vận động Stamford Bridge thuộc về đội bóng nào?',
        a: 'Arsenal',
        b: 'Chelsea',
        c: 'Tottenham',
        d: 'West Ham',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 9,
        question: 'Số áo đặc trưng của Messi trong màu áo Barcelona là số mấy?',
        a: '7',
        b: '10',
        c: '11',
        d: '9',
        correctAns: '10',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 10,
        question: 'Đội nào là kình địch truyền kiếp của Real Madrid?',
        a: 'Atletico Madrid',
        b: 'Barcelona',
        c: 'Sevilla',
        d: 'Valencia',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 11,
        question: 'Đội tuyển quốc gia nào của Nam Mỹ có biệt danh "Albiceleste"?',
        a: 'Brazil',
        b: 'Chile',
        c: 'Argentina',
        d: 'Uruguay',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 12,
        question: 'Ai là cầu thủ ghi nhiều bàn thắng nhất trong lịch sử Premier League?',
        a: 'Alan Shearer',
        b: 'Wayne Rooney',
        c: 'Thierry Henry',
        d: 'Sergio Agüero',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 13,
        question: 'Tuyển quốc gia nào tổ chức World Cup 2018?',
        a: 'Brazil',
        b: 'Russia',
        c: 'Qatar',
        d: 'Germany',
        correctAns: 'b',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 14,
        question: 'HLV nổi tiếng dẫn dắt Barcelona với chiến thuật tiki-taka là ai?',
        a: 'Pep Guardiola',
        b: 'Jose Mourinho',
        c: 'Carlo Ancelotti',
        d: 'Diego Simeone',
        correctAns: 'a',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
    {
        id: 15,
        question: 'Giải bóng đá nào là cao nhất tại Anh?',
        a: 'Championship',
        b: 'League One',
        c: 'Premier League',
        d: 'League Two',
        correctAns: 'c',
        userAns: null,
        isCorrect: null,
        level: 1,
        status: true
    },
];
