export const questions = [
    {
    id: 1,
    question: "Ai là Chủ tịch nước đầu tiên của nước Việt Nam Dân chủ Cộng hòa?",
    a: "Trường Chinh",
    b: "Hồ Chí Minh",
    c: "Phạm Văn Đồng",
    d: "Võ Nguyên Giáp",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
},
{
    id: 2,
        question: "Ngày Quốc khánh của Việt Nam là ngày nào?",
    a: "19/8",
    b: "1/5",
    c: "2/9",
    d: "30/4",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
},
{
    id: 3,
        question: "Chiến thắng Điện Biên Phủ diễn ra vào năm nào?",
    a: "1952",
    b: "1953",
    c: "1954",
    d: "1955",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
},
{
    id: 4,
        question: "Bác Hồ sinh năm bao nhiêu?",
    a: "1889",
    b: "1890",
    c: "1891",
    d: "1892",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 1,
    status: true,
},


{
    id: 5,
        question: "Cuộc khởi nghĩa Hai Bà Trưng chống lại ách đô hộ của nước nào?",
    a: "Chiêm Thành",
    b: "Mông Cổ",
    c: "Trung Quốc",
    d: "Pháp",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 2,
    status: true,
},
{
    id: 6,
        question: "Chiến thắng Bạch Đằng năm 938 do ai lãnh đạo?",
    a: "Lê Lợi",
    b: "Ngô Quyền",
    c: "Lý Thường Kiệt",
    d: "Trần Hưng Đạo",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 2,
    status: true,
},
{
    id: 7,
        question: "Chủ trương 'Toàn dân kháng chiến' được đề ra trong hoàn cảnh nào?",
    a: "Khởi nghĩa Nam Kỳ",
    b: "Chiến tranh chống Mỹ",
    c: "Toàn quốc kháng chiến chống Pháp",
    d: "Tổng tiến công Mậu Thân",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 2,
    status: true,
},
{
    id: 8,
        question: "Chiến thắng nào đã buộc Mỹ ngồi vào bàn đàm phán tại Paris năm 1973?",
    a: "Chiến dịch Điện Biên Phủ",
    b: "Chiến dịch Hồ Chí Minh",
    c: "Chiến dịch Tây Nguyên",
    d: "Chiến dịch Điện Biên Phủ trên không",
    correctAns: "d",
    userAns: null,
    isCorrect: null,
    level: 2,
    status: true,
},

// Level 3 - Trung bình
{
    id: 9,
        question: "Thành Thăng Long được vua nào đặt tên?",
    a: "Lê Thánh Tông",
    b: "Lý Thái Tổ",
    c: "Ngô Quyền",
    d: "Trần Nhân Tông",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 3,
    status: true,
},
{
    id: 10,
        question: "Chiến thắng Rạch Gầm - Xoài Mút diễn ra dưới triều đại nào?",
    a: "Nhà Trần",
    b: "Nhà Nguyễn",
    c: "Nhà Tây Sơn",
    d: "Nhà Lê",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 3,
    status: true,
},
{
    id: 11,
        question: "Ai là Tổng Bí thư đầu tiên của Đảng Cộng sản Việt Nam?",
    a: "Hà Huy Tập",
    b: "Nguyễn Văn Cừ",
    c: "Trần Phú",
    d: "Lê Duẩn",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 3,
    status: true,
},
{
    id: 12,
        question: "Hiệp định Genève được ký kết vào năm nào?",
    a: "1952",
    b: "1954",
    c: "1956",
    d: "1958",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 3,
    status: true,
},


{
    id: 13,
        question: "Tác phẩm 'Bình Ngô đại cáo' do ai viết?",
    a: "Nguyễn Trãi",
    b: "Nguyễn Du",
    c: "Chu Văn An",
    d: "Lê Thánh Tông",
    correctAns: "a",
    userAns: null,
    isCorrect: null,
    level: 4,
    status: true,
},
{
    id: 14,
        question: "Văn Miếu – Quốc Tử Giám được xây dựng dưới triều vua nào?",
    a: "Lý Thái Tổ",
    b: "Lý Nhân Tông",
    c: "Trần Nhân Tông",
    d: "Lê Thánh Tông",
    correctAns: "b",
    userAns: null,
    isCorrect: null,
    level: 4,
    status: true,
},
{
    id: 15,
        question: "Ai là người sáng lập triều đại nhà Tây Sơn?",
    a: "Nguyễn Huệ",
    b: "Nguyễn Lữ",
    c: "Nguyễn Nhạc",
    d: "Nguyễn Ánh",
    correctAns: "c",
    userAns: null,
    isCorrect: null,
    level: 4,
    status: true,
},
];


export const allOptions = ["a", "b", "c", "d"];

export const prizeMap = {
    0: 0,
    1: 200000,
    2: 500000,
    3: 1000000,
    4: 2000000,
    5: 3000000,
    6: 5000000,
    7: 7000000,
    8: 10000000,
    9: 14000000,
    10: 20000000,
    11: 30000000,
    12: 40000000,
    13: 60000000,
    14: 85000000,
    15: 150000000,
};